/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-12-06 19:59:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SummonerLookUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta content=\"text/html;charset=utf-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("\t<meta content=\"utf-8\" http-equiv=\"encoding\">\r\n");
      out.write("\t<title>SummonerLookUp</title>\r\n");
      out.write("\t<link href=\"assets/css/LoSStyleSheet.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<script>var __adobewebfontsappname__=\"dreamweaver\"</script><script src=\"http://use.edgefonts.net/electrolize:n4:default.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"4121\",secure:\"4126\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"body\" onload=\"Init2()\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/LeagueOfStalkJava/WebContent/SummonerLookUp.jsp\">\r\n");
      out.write("   <div class=\"header\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/LeagueOfStalkJava/WebContent/SummonerLookUp.jsp\">\r\n");
      out.write("   <div class=\"companyLogo\">League of Stalk</div>\r\n");
      out.write("\t   <form  action=\"SummonerLookup\" class=\"inputHeader\">\r\n");
      out.write("\t\t\t<input id=\"input\" name=\"summoner\" class=\"inputfieldHeader\">\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"button\" value=\"Stalk\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t   \r\n");
      out.write("<div class=\"summonerPreview\" id=\"sumPre\">\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("    <div class=\"summonerdata\">\r\n");
      out.write("                   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sIcon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"summonerIcon\" id=\"icon\">\r\n");
      out.write("                   <div class=\"stats\"> \r\n");
      out.write("                   <a id=\"name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a><br>\r\n");
      out.write("                   <a id=\"lvl\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lvl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a><br>\r\n");
      out.write("                   <a id=\"solo\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a><br>\r\n");
      out.write("                   <a id=\"flex\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devF}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a><br>\r\n");
      out.write("                   <a id=\"rank\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rank}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a><br>\r\n");
      out.write("                   <a id=\"kda\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </a><br>\r\n");
      out.write("                   <a id=\"prefPos\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prefferedPositions}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a><br>\r\n");
      out.write("                   <a id=\"Performance\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Performance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a><br></div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                <div class=\"summonerdata2\">   \r\n");
      out.write("               <div class=\"achievements\">Achivements<br><hr>-Pictures of Achievements-<br></div>\r\n");
      out.write("               <div class=\"bestChamps\">Most feared Champs<hr><table width=\"200\" border=\"0\" class=\"bestChamPictures\">\r\n");
      out.write("                   <tbody>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                       <td><img height=\"50px\" id=\"BestChamp1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bestChamp0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"/></td>\r\n");
      out.write("                       <td><img height=\"50px\" id=\"BestChamp2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bestChamp1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"/></td>\r\n");
      out.write("                       <td><img height=\"50px\" id=\"BestChamp3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bestChamp2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"/></td>\r\n");
      out.write("                       <td><img height=\"50px\" id=\"BestChamp4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bestChamp3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"/></td>\r\n");
      out.write("                       <td><img height=\"50px\" id=\"BestChamp5\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bestChamp4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"/></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                   </tbody>\r\n");
      out.write("               </table>\r\n");
      out.write("              </div> \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t   \r\n");
      out.write("<div class=\"tabs\">\r\n");
      out.write("  <button class=\"ReiterButtons\" onclick=\"openReiter('Overview')\">Overview</button> \r\n");
      out.write("  <button class=\"ReiterButtons\" onclick=\"openReiter('ChampionPerformance')\">Performance</button>\r\n");
      out.write("  <button class=\"ReiterButtons\" onclick=\"openReiter('Runes')\">Runes</button>\r\n");
      out.write("  <button class=\"ReiterButtons\" onclick=\"openReiter('Ingame')\">Ingame</button>\r\n");
      out.write("  <button class=\"ReiterButtons\" onclick=\"openReiter('Versus')\">Versus</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ChampionPerformance\" class=\"ReiterContent\">\r\n");
      out.write("\t<div class=\"ChampionList\">Champion Performances<hr>\r\n");
      out.write("\t  <table width=\"200\" border=\"0\" class=\"table\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\">\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  </tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\">\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\">\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\">\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c6\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c7\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c9\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t<td class=\"Champion\" >\r\n");
      out.write("\t\t\t\t<div class=\"Summarize\"><img src=\"1\" id=\"c10\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ChampionPerformance10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Overview\" class=\"ReiterContent\">\r\n");
      out.write("  Recent Matches\r\n");
      out.write("  <hr>\r\n");
      out.write("  <table width=\"200\" border=\"0\" class=\"table\">\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game1\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game2\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game3\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game4\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game5\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game6\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g6\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game7\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g7\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game8\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game9\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g9\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr><tr>\r\n");
      out.write("\t\t<td class=\"RecentMatchSummoner\" id=\"game10\">\r\n");
      out.write("\t\t\t<div class=\"Summarize\"><img src=\"http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentChamp9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" id=\"g10\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RecentMatchstats9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Runes\" class=\"ReiterContent\">\r\n");
      out.write("  Runes<hr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Ingame\" class=\"ReiterContent\">\r\n");
      out.write("\t Matchup<hr>\r\n");
      out.write("\t  <table width=\"200\" border=\"0\" class=\"matchupTable\">\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms1\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms2\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms3\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms4\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms5\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\r\n");
      out.write("\t  <tr><td>\r\n");
      out.write("\t\t<img src=\"1\" class=\"vsSign\">\r\n");
      out.write("\t  </td></tr>\r\n");
      out.write("\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms6\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms7\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms8\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms9\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"matchSummoner\" id=\"ms10\">\r\n");
      out.write("\t\t\t<div class=\"igs1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elo10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kda10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchChampKda10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>sad<br>asd</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("\t  \r\n");
      out.write("\t<div class=\"lanepressureMap\"><img src=\"1\" class=\"lanePress\"></div>\r\n");
      out.write("\t<div> approx. Winchance:</div>\r\n");
      out.write("\t<div>Matchup durschn. MMR</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("<div id=\"Versus\" class=\"ReiterContent\">\r\n");
      out.write(" vs Mate xyz<hr>\r\n");
      out.write("  <table width=\"200\" border=\"0\" class=\"recentMatchesTable\">\r\n");
      out.write("\t <tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"SummonerVergleich\" id=\"SummonerVergleich1\">\r\n");
      out.write("\t\t\t\t<div class=\"SummonerVergleichData\">yourstats</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"SummonerVergleich\" id=\"SummonerVergleich2\">\r\n");
      out.write("\t\t\t\t<div class=\"SummonerVergleichData\">your firendstats</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction openReiter(reitername) {\r\n");
      out.write("\t\tvar i, tabcontent, tablinks;\r\n");
      out.write("\t\ttabcontent = document.getElementsByClassName(\"ReiterContent\");\r\n");
      out.write("\t\tfor (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("\t\t\ttabcontent[i].style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttablinks = document.getElementsByClassName(\"ReiterButtons\");\r\n");
      out.write("\t\tfor (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("\t\t\ttablinks[i].className = tablinks[i].className.replace(\"active\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(reitername).style.display = \"block\";\r\n");
      out.write("\t\tevt.currentTarget.className += \" active\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Init(Sumbackround){\r\n");
      out.write("\t\tdocument.getElementById(\"sumPre\").style.background = url(Sumbackround);\r\n");
      out.write("\t\topenReiter('Overview');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Init2(){\r\n");
      out.write("\t\topenReiter('Overview');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
